services:
  - type: web
    name: arvi-stripe-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false        # la pondr√° a mano en Render
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUCCESS_BASE_URL
        value: "https://getarvi.com/success"
      - key: CANCEL_URL
        value: "https://getarvi.com/cancel"
